language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer require typo3/cms $TYPO3_VERSION

script:
  - composer test

jobs:
  include:
    - php: 5.6
      env: TYPO3_VERSION=^7.6
      script:
        - composer lint:php
        - composer test
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7

    - &lint
      php: 7.0
      env: PHP lint
      install:
        - composer install
      script:
        - composer lint:php
    - <<: *lint
      php: 7.1

    - stage: deploy
      if: tag IS present
      php: 7.1
      before_install: skip
      install: skip
      before_script: skip
      script: |
        echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"

        git reset --hard
        git clean -xfd

        export PATH=$PATH:$(composer global config bin-dir --absolute 2>/dev/null)
        composer global require helhum/ter-client

        echo "Uploading release ${TRAVIS_TAG} to TER"
        ter-client upload $(composer config extra.typo3/cms.extension-key) . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"

notifications:
  slack:
    secure: FHPbVXHOrXsk80e0+WLID8v5m9S59/qoQyM5XK2hytFUaT+oSh0iY+Ajdnajpl+6qd6iQNbREfd04A2TTBxh7+LzHgOqxhHoZSYTgTHgsOPQPgUCxPJpWInwQGxgp+23pE0l+oX8u0lWkYk9NIf+WtrF6niLvT0KLOJiuB8ojms=
